export type NavigationNode = { key: string; titleKey: string; href?: string; children?: NavigationNode[] };
const group = (key: string, titleKey: string, children: [string, string, string][]): NavigationNode => ({ key, titleKey, children: children.map(([childKey, childTitleKey, href]) => ({ key: childKey, titleKey: childTitleKey, href })) });
export const navigationTree: NavigationNode[] = [
  { key: 'dashboard', titleKey: 'dashboard', href: '/dashboard' },
  group('diagnosis', 'diagnosis', [['citation-detection','citationDetection','/diagnosis/citation-detection'],['competitor-comparison','competitorComparison','/diagnosis/competitor-comparison'],['asset-audit','assetAudit','/diagnosis/asset-audit'],['channel-map','channelMap','/diagnosis/channel-map'],['comprehensive-report','comprehensiveReport','/diagnosis/comprehensive-report']]),
  group('improvement', 'improvement', [['optimization-work-orders','optimizationWorkOrders','/improvement/optimization-work-orders'],['keyword-matrix','keywordMatrix','/improvement/keyword-matrix'],['source-building','sourceBuilding','/improvement/source-building'],['technical-adaptation','technicalAdaptation','/improvement/technical-adaptation'],['content-production','contentProduction','/improvement/content-production']]),
  group('verification', 'verification', [['visibility-trend','visibilityTrend','/verification/visibility-trend'],['rank-tracking','rankTracking','/verification/rank-tracking'],['attribution','attribution','/verification/attribution'],['comparison-test','comparisonTest','/verification/comparison-test'],['periodic-retest','periodicRetest','/verification/periodic-retest']]),
  group('admin', 'admin', [['brands','brands','/admin/brands'],['engines','engines','/admin/engines'],['models','models','/admin/models'],['rag-agents','ragAgents','/admin/rag-agents']]),
];
