export type NavigationNode = { key: string; titleKey: string; icon: string; href?: string; children?: NavigationNode[] };
type NavigationItem = [string, string, string, string];
const group = (key: string, titleKey: string, icon: string, children: NavigationItem[]): NavigationNode => ({ key, titleKey, icon, children: children.map(([childKey, childTitleKey, childIcon, href]) => ({ key: childKey, titleKey: childTitleKey, icon: childIcon, href })) });
export const navigationTree: NavigationNode[] = [
  { key: 'dashboard', titleKey: 'dashboard', icon: 'layout-dashboard', href: '/dashboard' },
  group('configuration', 'configuration', 'settings', [['basic-configuration','basicConfiguration','sliders-horizontal','/configuration/basic'],['brand-questions','brandQuestions','messages-square','/configuration/questions'],['competitors','competitors','git-compare-arrows','/configuration/competitors'],['brand-facts','brandFacts','book-open-check','/configuration/brand-facts']]),
  group('diagnosis', 'diagnosisRoom', 'stethoscope', [['diagnosis-execution','diagnosisExecution','circle-play','/diagnosis/diagnosis-execution'],['diagnosis-report','diagnosisReport','file-chart-column','/diagnosis/diagnosis-report'],['problem-summary','problemSummary','list-checks','/diagnosis/problem-summary'],['competitor-comparison','competitorComparison','git-compare-arrows','/diagnosis/competitor-comparison'],['diagnosis-samples','diagnosisSamples','file-search','/diagnosis/samples'],['positioning-map','positioningMap','map','/diagnosis/positioning-map']]),
  group('improvement', 'improvement', 'trending-up', [['optimization-work-orders','optimizationWorkOrders','clipboard-list','/improvement/optimization-work-orders'],['keyword-matrix','keywordMatrix','grid-2x2','/improvement/keyword-matrix'],['source-building','sourceBuilding','network','/improvement/source-building'],['technical-adaptation','technicalAdaptation','wrench','/improvement/technical-adaptation'],['content-production','contentProduction','pen-line','/improvement/content-production']]),
  group('verification', 'verification', 'badge-check', [['visibility-trend','visibilityTrend','chart-no-axes-combined','/verification/visibility-trend'],['rank-tracking','rankTracking','trophy','/verification/rank-tracking'],['attribution','attribution','chart-pie','/verification/attribution'],['comparison-test','comparisonTest','split','/verification/comparison-test'],['periodic-retest','periodicRetest','calendar-clock','/verification/periodic-retest']]),
  group('admin', 'admin', 'settings', [['brands','brands','tags','/admin/brands'],['engines','engines','bot','/admin/engines'],['models','models','boxes','/admin/models'],['rag-agents','ragAgents','brain-circuit','/admin/rag-agents']]),
];
