import { requestJson } from '@/lib/api';

export type RunMetrics = { sampleCount: number; successfulSampleRate: number; visibilityRate: number };
export type TrendRun = { runId: number; status: 'succeeded' | 'partial'; createdAt: string; finishedAt: string | null; configuration: { market: string | null; questionCount: number; engineCount: number; samplingMethod: string; rulesVersion: string } | null; metrics: RunMetrics };
export type VisibilityTrend = { runs: TrendRun[] };
export type QuestionTracking = { runs: Array<{ runId: number; status: string; finishedAt: string | null }>; questions: Array<{ id: number; question: string; group: string; points: Array<{ runId: number; finishedAt: string | null } & RunMetrics> }> };
export type RunComparison = { id: number; baselineRunId: number; retestRunId: number; comparability: 'comparable' | 'partial' | 'incomparable'; reasons: string[]; metrics: { sharedQuestionIds: number[]; sharedEngineIds: number[]; baseline: RunMetrics; retest: RunMetrics; delta: Pick<RunMetrics, 'visibilityRate' | 'successfulSampleRate'> } | null };
export type Attribution = { id: number; workOrderId: number; comparisonId: number; conclusion: 'confirmed' | 'possible' | 'inconclusive' | 'no_impact'; rationale: string | null; confirmedBy: string | null; createdAt: string };
export type ManualAttributionConclusion = Exclude<Attribution['conclusion'], 'possible'>;
export type FullConfigurationRetestScope = { mode: 'all_configured' };
export type PeriodicRetestPlan = { id: number; baselineRunId: number | null; frequency: 'weekly' | 'monthly' | 'quarterly'; scope: FullConfigurationRetestScope; notification: Record<string, unknown>; enabled: boolean; lastRunId: number | null; lastTriggeredAt: string | null };
export type ComparisonExperiment = { id: number; name: string; controlScope: Record<string, unknown>; treatmentScope: Record<string, unknown>; successMetrics: Record<string, unknown>; version: number; supersedesExperimentId: number | null; controlRunId: number | null; treatmentRunId: number | null; status: 'draft' | 'running' | 'completed' | 'cancelled' | 'superseded' };

export function getVisibilityTrend(brandId: number) { return requestJson<VisibilityTrend>(`brands/${brandId}/verification/trend`); }
export function getQuestionTracking(brandId: number) { return requestJson<QuestionTracking>(`brands/${brandId}/verification/questions`); }
export function compareDiagnosisRuns(brandId: number, baselineRunId: number, retestRunId: number) {
  return requestJson<RunComparison>(`brands/${brandId}/verification/comparisons`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ baselineRunId, retestRunId }) });
}
export function getAttributions(brandId: number) { return requestJson<Attribution[]>(`brands/${brandId}/verification/attributions`); }
export function createAttribution(brandId: number, value: Omit<Attribution, 'id' | 'createdAt' | 'conclusion'> & { conclusion: ManualAttributionConclusion }) { return requestJson<Attribution>(`brands/${brandId}/verification/attributions`, { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(value) }); }
export function getPeriodicRetestPlans(brandId: number) { return requestJson<PeriodicRetestPlan[]>(`brands/${brandId}/verification/periodic-retests`); }
export function createPeriodicRetestPlan(brandId: number, value: Pick<PeriodicRetestPlan, 'frequency' | 'scope' | 'notification' | 'baselineRunId' | 'enabled'>) { return requestJson<PeriodicRetestPlan>(`brands/${brandId}/verification/periodic-retests`, { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(value) }); }
export function updatePeriodicRetestPlan(brandId: number, planId: number, value: Partial<Pick<PeriodicRetestPlan, 'frequency' | 'scope' | 'notification' | 'baselineRunId' | 'enabled'>>) { return requestJson<PeriodicRetestPlan>(`brands/${brandId}/verification/periodic-retests/${planId}`, { method: 'PATCH', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(value) }); }
export function triggerPeriodicRetest(brandId: number, planId: number) { return requestJson<{plan: PeriodicRetestPlan; run: {id: number}}>(`brands/${brandId}/verification/periodic-retests/${planId}/trigger`, { method: 'POST' }); }
export function getComparisonExperiments(brandId: number) { return requestJson<ComparisonExperiment[]>(`brands/${brandId}/verification/comparison-experiments`); }
export function createComparisonExperiment(brandId: number, value: Pick<ComparisonExperiment, 'name' | 'controlScope' | 'treatmentScope' | 'successMetrics'>) { return requestJson<ComparisonExperiment>(`brands/${brandId}/verification/comparison-experiments`, { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(value) }); }
export function replaceComparisonExperiment(brandId: number, experimentId: number, value: Pick<ComparisonExperiment, 'name' | 'controlScope' | 'treatmentScope' | 'successMetrics'>) { return requestJson<ComparisonExperiment>(`brands/${brandId}/verification/comparison-experiments/${experimentId}`, { method: 'PUT', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(value) }); }
export function evaluateComparisonExperiment(brandId: number, experimentId: number, value: {controlRunId: number; treatmentRunId: number}) { return requestJson<{experiment: ComparisonExperiment; comparison: RunComparison; note: string}>(`brands/${brandId}/verification/comparison-experiments/${experimentId}/evaluate`, { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(value) }); }
