'use client';

import { Icon } from '@iconify/react';
import { useTranslations } from 'next-intl';
import { useWorkspaceStore } from '@/stores/workspace-store';

const scoreCards = [
  { key: 'citation', icon: 'lucide:quote', tone: 'text-emerald-600 dark:text-emerald-400', value: '36%', delta: '+8.4%' },
  { key: 'competition', icon: 'lucide:git-compare-arrows', tone: 'text-amber-600 dark:text-amber-400', value: '3 / 5', delta: '需提升' },
  { key: 'assets', icon: 'lucide:file-search', tone: 'text-blue-600 dark:text-blue-400', value: '78', delta: '12 待修复' },
  { key: 'channels', icon: 'lucide:map', tone: 'text-violet-600 dark:text-violet-400', value: '6', delta: '覆盖渠道' },
];

export function DiagnosisInsightsPage(): React.JSX.Element {
  const t = useTranslations('DiagnosisInsights');
  const brand = useWorkspaceStore((state) => state.brands.find((item) => item.id === state.currentBrandId) ?? null);
  return <section className="pb-8">
    <header className="mb-6 border-b border-[var(--border)] pb-4"><h1 className="mb-2 text-[22px] font-semibold">{t('title')}</h1><p className="text-sm leading-6 text-[var(--muted-foreground)]">{t('description')}</p></header>
    <div className="mb-5 rounded-lg border border-[var(--border)] bg-[var(--card)] p-4 text-sm"><span className="text-[var(--muted-foreground)]">{t('brandLabel')}</span>{brand?.name ?? t('noBrand')}<span className="ml-5 text-[var(--muted-foreground)]">{t('sampleNote')}</span></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{scoreCards.map((card) => <article key={card.key} className="rounded-lg border border-[var(--border)] bg-[var(--card)] p-4"><div className="flex items-center justify-between"><p className="text-sm text-[var(--muted-foreground)]">{t(`cards.${card.key}.title`)}</p><Icon icon={card.icon} className={`size-4 ${card.tone}`} /></div><p className="mt-3 text-2xl font-semibold">{card.value}</p><p className={`mt-1 text-xs ${card.tone}`}>{card.delta}</p></article>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(0,0.8fr)]"><section className="rounded-lg border border-[var(--border)] bg-[var(--card)] p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">{t('visibilityTitle')}</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">{t('visibilityDescription')}</p></div><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-xs text-emerald-700 dark:text-emerald-300">{t('improving')}</span></div><div className="grid h-36 grid-cols-8 items-end gap-2 border-b border-[var(--border)] pb-2">{[34, 42, 38, 51, 47, 62, 57, 71].map((height, index) => <div key={index} className="rounded-t bg-[var(--primary)]/80" style={{ height: `${height}%` }} />)}</div><div className="mt-2 flex justify-between text-xs text-[var(--muted-foreground)]"><span>7/18</span><span>7/25</span><span>8/01</span><span>8/08</span></div></section><section className="rounded-lg border border-[var(--border)] bg-[var(--card)] p-4"><h2 className="font-semibold">{t('priorityTitle')}</h2><div className="mt-4 space-y-3">{['aiAccess', 'citationGap', 'assetFix'].map((key, index) => <div key={key} className="flex gap-3"><span className={`mt-1 size-2 shrink-0 rounded-full ${index === 0 ? 'bg-red-500' : index === 1 ? 'bg-amber-500' : 'bg-blue-500'}`} /><div><p className="text-sm font-medium">{t(`priorities.${key}.title`)}</p><p className="mt-1 text-xs leading-5 text-[var(--muted-foreground)]">{t(`priorities.${key}.detail`)}</p></div></div>)}</div></section></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-lg border border-[var(--border)] bg-[var(--card)] p-4"><div className="mb-4 flex items-center gap-2"><Icon icon="lucide:quote" className="size-4 text-emerald-600 dark:text-emerald-400" /><h2 className="font-semibold">{t('citationTitle')}</h2></div><div className="space-y-3">{['ChatGPT', 'Kimi', '文心一言'].map((engine, index) => <div key={engine} className="grid grid-cols-[94px_1fr_auto] items-center gap-3 text-sm"><span>{engine}</span><div className="h-2 overflow-hidden rounded-full bg-[var(--muted)]"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${[58, 42, 31][index]}%` }} /></div><span className="text-[var(--muted-foreground)]">{[58, 42, 31][index]}%</span></div>)}</div></section><section className="rounded-lg border border-[var(--border)] bg-[var(--card)] p-4"><div className="mb-4 flex items-center gap-2"><Icon icon="lucide:map" className="size-4 text-violet-600 dark:text-violet-400" /><h2 className="font-semibold">{t('channelTitle')}</h2></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{['官网内容', '知乎', '小红书', '行业媒体', '视频平台', '问答社区'].map((channel, index) => <div key={channel} className="rounded-md bg-[var(--muted)] p-3"><p className="text-sm">{channel}</p><p className={`mt-2 text-xs ${index < 3 ? 'text-emerald-600 dark:text-emerald-400' : 'text-amber-600 dark:text-amber-400'}`}>{index < 3 ? t('covered') : t('gap')}</p></div>)}</div></section></div>
  </section>;
}
