'use client';

import { ResourceManagementPage, type ResourceConfig } from '@/components/admin/resource-management-page';
import {WebReviewActions, WebReviewStatusCell} from '@/components/engines/web-review-status-cell';
import {useTranslations} from 'next-intl';

type VerificationGuidance = {purposeTitle: string; automaticTitle: string; manualTitle: string; purpose: string; automatic: string; manual: string};

function resources(t: ReturnType<typeof useTranslations>): Record<string, ResourceConfig> {
  const field = (key: string, label: string, type?: 'text' | 'textarea' | 'number' | 'checkbox' | 'multiselect', required?: boolean, optionsEndpoint?: string, inverse?: boolean) => ({key, label, type, required, optionsEndpoint, inverse});
  const status = (item: {disabled?: unknown}) => item.disabled === true ? t('disabled') : t('enabled');
  const localTime = (item: Record<string, unknown>, key: 'createdAt' | 'updatedAt') => {
    const value = item[key];
    return value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'medium' }).format(new Date(String(value))) : t('none');
  };
  return {
    brands: { endpoint: 'brands', title: t('brands.title'), singular: t('brands.singular'), description: t('brands.description'), fields: [field('name', t('name'), 'text', true), field('code', t('code'), 'text', true), field('website', t('website')), field('industry', t('industry')), field('description', t('descriptionField'), 'textarea'), field('engineIds', t('diagnosticEngines'), 'multiselect', false, 'engines'), field('disabled', t('enabled'), 'checkbox', false, undefined, true)], filters: [{key: 'disabled', label: t('allStatus'), type: 'boolean'}], columns: [{key: 'name', label: t('name'), sortable: true}, {key: 'code', label: t('code'), sortable: true}, {key: 'industry', label: t('industry'), sortable: true}, {key: 'disabled', label: t('status'), sortable: true, render: status}, {key: 'createdAt', label: t('createdAt'), sortable: true, render: (item) => localTime(item, 'createdAt')}, {key: 'updatedAt', label: t('updatedAt'), sortable: true, render: (item) => localTime(item, 'updatedAt')}] },
    engines: { endpoint: 'engines', title: t('engines.title'), singular: t('engines.singular'), description: t('engines.description'), fields: [field('name', t('name'), 'text', true), field('code', t('code'), 'text', true), field('vendor', t('vendor'), 'text', true), field('modelName', t('modelName')), field('baseUrl', t('baseUrl')), field('apiKey', t('apiKey')), field('webSearchEnabled', t('nativeWebSearch'), 'checkbox'), field('description', t('descriptionField'), 'textarea'), field('disabled', t('disabled'), 'checkbox')], filters: [{key: 'vendor', label: t('vendor')}, {key: 'disabled', label: t('allStatus'), type: 'boolean'}], columns: [{key: 'name', label: t('name'), sortable: true}, {key: 'code', label: t('code'), sortable: true}, {key: 'vendor', label: t('vendor'), sortable: true}, {key: 'disabled', label: t('status'), sortable: true, render: status}, {key: 'updatedAt', label: t('updatedAt'), sortable: true, render: (item) => localTime(item, 'updatedAt')}, {key: 'webReview', label: t('webReview.status'), render: (item) => <WebReviewStatusCell engine={{id: item.id, webReview: item.webReview as never}} />}], actionColumnWidth: 210, renderActions: (item, onChanged) => <WebReviewActions engine={{id: item.id}} onChanged={onChanged} /> },
    models: { endpoint: 'models', title: t('models.title'), singular: t('models.singular'), description: t('models.description'), fields: [field('name', t('name'), 'text', true), field('modelName', t('modelName'), 'text', true), field('provider', t('provider'), 'text', true), field('baseUrl', t('baseUrl')), field('apiKey', t('apiKey')), field('disabled', t('disabled'), 'checkbox')], filters: [{key: 'provider', label: t('provider')}, {key: 'disabled', label: t('allStatus'), type: 'boolean'}, {key: 'isDefault', label: t('allDefaultStatus'), type: 'boolean'}], columns: [{key: 'name', label: t('name'), sortable: true}, {key: 'modelName', label: t('modelName'), sortable: true}, {key: 'provider', label: t('provider'), sortable: true}, {key: 'disabled', label: t('status'), sortable: true, render: status}, {key: 'isDefault', label: t('default'), sortable: true, render: (item) => item.isDefault ? t('defaultModel') : t('none')}, {key: 'createdAt', label: t('createdAt'), sortable: true, render: (item) => localTime(item, 'createdAt')}, {key: 'updatedAt', label: t('updatedAt'), sortable: true, render: (item) => localTime(item, 'updatedAt')}] },
    'rag-agents': { endpoint: 'rag-agents', title: t('ragAgents.title'), singular: t('ragAgents.singular'), description: t('ragAgents.description'), fields: [field('name', t('name'), 'text', true), field('code', t('code'), 'text', true), field('brandId', t('brandId'), 'number', true), field('modelId', t('modelId'), 'number', true), field('description', t('descriptionField'), 'textarea'), field('systemPrompt', t('systemPrompt'), 'textarea'), field('disabled', t('disabled'), 'checkbox')], filters: [{key: 'brandId', label: t('brandId')}, {key: 'modelId', label: t('modelId')}, {key: 'disabled', label: t('allStatus'), type: 'boolean'}], columns: [{key: 'name', label: t('name'), sortable: true}, {key: 'code', label: t('code'), sortable: true}, {key: 'brandId', label: t('brandId'), sortable: true}, {key: 'modelId', label: t('modelId'), sortable: true}, {key: 'disabled', label: t('status'), sortable: true, render: status}, {key: 'createdAt', label: t('createdAt'), sortable: true, render: (item) => localTime(item, 'createdAt')}, {key: 'updatedAt', label: t('updatedAt'), sortable: true, render: (item) => localTime(item, 'updatedAt')}] },
  };
}

export function WorkspacePage({ title, description, admin, guidance }: { title?: string; description?: string; admin?: string; guidance?: VerificationGuidance }): React.JSX.Element | null {
  const t = useTranslations('Management');
  const pageT = useTranslations('Pages');
  const configs = resources(t);
  if (admin && configs[admin]) return <ResourceManagementPage config={configs[admin]} />;
  return <section><header className="mb-[22px] border-b border-[var(--border)] pb-4"><h1 className="mb-[7px] text-[22px] font-semibold">{title}</h1><p className="text-[var(--muted-foreground)]">{description}</p></header>{guidance && <section className="mb-5 rounded-[10px] border border-[var(--border)] bg-[var(--card)] p-5"><h2 className="text-sm font-semibold">{guidance.purposeTitle}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{guidance.purpose}</p><div className="mt-5 grid gap-5 md:grid-cols-2"><div><h2 className="text-sm font-semibold">{guidance.automaticTitle}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{guidance.automatic}</p></div><div><h2 className="text-sm font-semibold">{guidance.manualTitle}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{guidance.manual}</p></div></div></section>}<div className="rounded-[10px] border border-[var(--border)] bg-[var(--card)] p-5"><p className="text-[var(--muted-foreground)]">{pageT('placeholder')}</p></div></section>;
}
