import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectDataSource, InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { CreateModelDto, ListModelDto, UpdateModelDto } from './models.dto';
import { ModelEntity } from './model.entity';

@Injectable()
export class ModelsService {
  constructor(@InjectRepository(ModelEntity) private readonly repository: Repository<ModelEntity>, @InjectDataSource() private readonly dataSource: DataSource) {}
  async list(query: ListModelDto) { const page = Number(query.page) || 1; const pageSize = Number(query.pageSize) || 20; const builder = this.repository.createQueryBuilder('model').where('model.deleted = :deleted', { deleted: false }); const keyword = query.keyword?.trim(); if (keyword) builder.andWhere('(model.name LIKE :keyword OR model.modelName LIKE :keyword OR model.provider LIKE :keyword)', { keyword: `%${keyword}%` }); if (query.provider?.trim()) builder.andWhere('model.provider = :provider', { provider: query.provider.trim() }); if (query.disabled !== undefined) builder.andWhere('model.disabled = :disabled', { disabled: query.disabled }); if (query.isDefault !== undefined) builder.andWhere('model.isDefault = :isDefault', { isDefault: query.isDefault }); const fields: Record<string, string> = { name: 'model.name', modelName: 'model.modelName', provider: 'model.provider', disabled: 'model.disabled', isDefault: 'model.isDefault', createdAt: 'model.created_at', updatedAt: 'model.updated_at' }; const field = fields[query.sortBy ?? ''] ?? 'model.name'; const direction = query.sortOrder?.toUpperCase() === 'DESC' ? 'DESC' : 'ASC'; const [items, total] = await builder.orderBy(field, direction).skip((page - 1) * pageSize).take(pageSize).getManyAndCount(); return { items: items.map((item) => this.toResponse(item)), total, page, pageSize }; }
  async findOne(id: number) { const item = await this.repository.findOne({ where: { id, deleted: false } }); if (!item) throw new NotFoundException(`Model ${id} 不存在`); return item; }
  async create(dto: CreateModelDto) { return this.toResponse(await this.save(this.repository.create({ ...dto, apiKey: dto.apiKey?.trim() || null }))); }
  async update(id: number, dto: UpdateModelDto) { const item = await this.findOne(id); const { apiKey, ...rest } = dto; Object.assign(item, rest); if (apiKey !== undefined) item.apiKey = apiKey.trim() || null; return this.toResponse(await this.save(item)); }
  async setDefault(id: number) { return this.dataSource.transaction(async (manager) => { const repository = manager.getRepository(ModelEntity); await repository.createQueryBuilder().update(ModelEntity).set({ isDefault: false }).where('deleted = :deleted', { deleted: false }).execute(); const item = await repository.findOne({ where: { id, deleted: false } }); if (!item) throw new NotFoundException(`Model ${id} 不存在`); item.isDefault = true; return this.toResponse(await repository.save(item)); }); }
  async remove(id: number) { const item = await this.findOne(id); item.deleted = true; item.disabled = true; item.deletedAt = new Date(); await this.repository.save(item); return { deleted: true, id }; }
  private async save(item: ModelEntity) { try { return await this.repository.save(item); } catch { throw new ConflictException('Model 名称已存在'); } }
  toResponse(item: ModelEntity) { const key = item.apiKey; return { id: item.id, name: item.name, modelName: item.modelName, provider: item.provider, baseUrl: item.baseUrl, disabled: item.disabled, deleted: item.deleted, isDefault: item.isDefault, createdAt: item.createdAt, updatedAt: item.updatedAt, deletedAt: item.deletedAt, apiKeyConfigured: Boolean(key), apiKeyMasked: key ? `${key.slice(0, 3)}…${key.slice(-4)}` : null }; }
}
